### ISSUE TITLE
Poder cargar assets propios y fix duplicado

### ISSUE THREAD

**Issue by fbalboadv** [TaaroBravo/RaceEditor#3]
Que se pueda con AssetDatabase (no resources) tener una carpeta con todos los prefabs. Mientras siga algún criterio que se levante sólo si es una curva, recto, salida, etc.
Además, arreglar que los tiles se duplican cuando se crean.

**Comment by DarioColo** [comment]
Terminado, con minimas modificaciones con respecto a la consigna dado que de los tiles se encarga Lautaro.
